spring:
  cloud:
    nacos:
      server-addr: ${TJ_NACOS_ADDR:192.168.127.101:8848}
      username: nacos
      password: nacos
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        namespace: f923fb34-cb0a-4c06-8fca-ad61ea61a3f0
        group: DEFAULT_GROUP
        ip: ${TJ_HOST:127.0.0.1}
  config:
    import:
      - nacos:${spring.application.name}.yaml
      - nacos:shared-spring.yaml
      - nacos:shared-redis.yaml
      - nacos:shared-logs.yaml
      - nacos:shared-feign.yaml
      - nacos:shared-mybatis.yaml
logging:
  level:
    com:
      #      alibaba: debug
      tianji: debug
#    org:
#      springframework:
#        ai:
#          chat:
#            client:
#              advisor: DEBUG
#      apache:
#        hc:
#          client5:
#            http:
#              wire: debug
